# These services are not meant to be run simultaneously.
# The dev service is intented for local development, the release service is intented for production
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/usr/rc/app
  release:
    build:
      context: .
      target: release