# These services are not meant to be run simultaneously.
# The dev service is intended for local development, the release service is intended for "production"
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/usr/rc/app
  release:
    build:
      context: .
      target: release